# DataBase
spring:
  datasource:
    url: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        # 1. 서비스 제공자에 대한 정보
        # redirect 할 로그인 페이지가 어딘지
        # access token 을 발급받는 URL 이 어딘지
        # access token 을 제공하여 사용자 정보를 회수할 URL 은 어딘지
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        # 2. 서비스 제공자를 사용하기 위한 정보
        # 클라이언트(즉 우리 서버)를 식별하기 위한 정보
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: /auth/oauth/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: ODIK
            scope:
              - email
              - profile

# Token Password
token:
  email: "oe"

# Image PATH
file:
  upload:
    path: "./file"
    url: "/file"

# JWT
jwt:
  secret: JEh7781T69H7/BGxUTl7wX538jGYOe52
  accessTokenExpirationTime: 3600000
  refreshTokenExpirationTime: 86400000
