# DataBase
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/odik
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  profiles:
#    include: oauth
#  security:
#    oauth2:
#      client:
#        # 1. 서비스 제공자에 대한 정보
#        # redirect 할 로그인 페이지가 어딘지
#        # access token 을 발급받는 URL 이 어딘지
#        # access token 을 제공하여 사용자 정보를 회수할 URL 은 어딘지
#        provider:
#          google :
#            authorization-uri:
#            token-uri:
#            user-info-uri:
#            user-name-attribute:
#        # 2. 서비스 제공자를 사용하기 위한 정보
#        # 클라이언트(즉 우리 서버)를 식별하기 위한 정보
#        registration:
#          google:
#            client-id:
#            client-secret:
#            redirect-uri:
#            authorization-grant-type:
#            client-authentication-method:
#            client-name:
#            scope:
#          # 서비스 제공자 식별자

# Image PATH
file:
  upload:
    path: "./file"
    url: "/file"

# JWT
jwt:
  secret: JEh7781T69H7/BGxUTl7wX538jGYOe52
  accessTokenExpirationTime: 3600000
  refreshTokenExpirationTime: 86400000